spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: crate-drop